### ISSUE TITLE
Improve Danger messages

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd-regression-tester#38]
At the moment Danger messages are very basic, just saying that either no meaningful report is needed (ie: no Java changes), or to check out the report.

However, I believe we could do better...

1. State how many new violations were introduced
2. State how many violations were removed
3. State how many new errors were introduced
4. State how many error have been removed

So, we could have messages such as:

> This changeset introduces 3 new violations, and removes 1 error. [Full Report](xxx)

> This changeset removes 2 violations, adds 1 error and removes 2 errors. [Full Report](xxx)

> This changeset produces no differences. [Full Report](xxx)

That way, contributors have a better understanding of what may be wrong with their PR, and we know what to expect from the changeset. Otherwise, we end this PRs such as [this one](https://github.com/pmd/pmd/pull/1302#issuecomment-412639659), opening the report to see nothing changed.

**Comment by djydewang** [comment]
@jsotuyod 
Thank you for your proposal. I‘ll fix the issue before releasing the final version of pmdtester-1.0.0
