### ISSUE TITLE
Support auxclasspath / typeresolution

### ISSUE THREAD

**Issue by adangel** [pmd/pmd-regression-tester#48]
We execute PMD just on the source code of standard projects now, but specifying the classpath for libraries used by the source code is also crucial for the type resolution.

This means, we probably need to build the project, we are analyzing, first.
And then figure out the full auxclasspath for the project.
We probably need then a small "build recipe" in addition to the source url for each project.

We could limit ourselves first for maven projects and execute `mvn compile` first. We still need to figure out the complete classpath though, which can be even more trickier for multi-module projects.

**Comment by oowekyala** [comment]
Can we use [`mvn dependency:build-classpath`](https://maven.apache.org/plugins/maven-dependency-plugin/build-classpath-mojo.html) to resolve dependencies?

**Comment by adangel** [comment]
> Can we use [`mvn dependency:build-classpath`](https://maven.apache.org/plugins/maven-dependency-plugin/build-classpath-mojo.html) to resolve dependencies?

That looks like it should work. As long as the project uses maven, of course.

For building/build recipe, maybe we can borrow something from reproducible builds? For pmd, it looks like this: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/net/sourceforge/pmd/pmd-6.27.0.buildspec

```
command="mvn -Ppmd-release clean package -DskipTests -Dmaven.javadoc.skip -Dgpg.skip"
```

**Comment by oowekyala** [comment]
> For building/build recipe, maybe we can borrow something from reproducible builds? For pmd, it looks like this: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/net/sourceforge/pmd/pmd-6.27.0.buildspec

This looks really cool. It might be possible to use reproducible-central's `rebuild.sh` directly. But then, maybe we might as well download the artifact from central? They're supposed to be identical after all.

**Comment by adangel** [comment]
> But then, maybe we might as well download the artifact from central?

That would work for the main artifact, but the test sources are not published.

The following commands work for checkstyle:

```
pushd repositories/checkstyle
mvn test-compile
mvn dependency:build-classpath -DincludeScope=test -Dmdep.outputFile=classpath.txt
popd

pmd-bin-7.0.0-SNAPSHOT/bin/run.sh pmd -R category/java/documentation.xml/CommentRequired \
    -d repositories/checkstyle/src/it/java/com/google/checkstyle/test/chapter2filebasic/rule21filename/OuterTypeFilenameTest.java \
    -auxclasspath repositories/checkstyle/target/classes:repositories/checkstyle/target/test-classes:$(cat repositories/checkstyle/classpath.txt)
```

springframework is a bit more difficult (and it uses gradle...)

**Comment by adangel** [comment]
First preview of checkstyle comparing pmd/pmd#2802 against master is available: https://chunk.pmd-code.org/pmd/f465ddd3-2188-4976-9f61-f16591faea2c/diff/index.html
The numbers look much better now....
