### ISSUE TITLE
Support configuration errors in the report

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd-regression-tester#57]
The report on pmd/pmd#1470 initially showed that violations had been removed, but that is because the rule had been removed from the ruleset as dysfunctional, because of the following changeset:

https://github.com/pmd/pmd/pull/1470/files#diff-4036d2a214e817321e2fb7694ea0aba2R241 

The report should have shown that new configuration errors were reported.

**Comment by adangel** [comment]
Example error:

    <configerror rule="LoosePackageCoupling" msg="No packages or classes specified"/>

Schema:
https://github.com/pmd/pmd/blob/master/pmd-core/src/main/resources/report_2_0_0.xsd

There can be 0 or more configerror elements.
