### ISSUE TITLE
Better HTML presentation for diff report

### ISSUE THREAD

**Issue by adangel** [pmd/pmd-regression-tester#73]
The table is very bulky and not helpful, if you want to look at a specific rule/file.

The idea is, to have a table, that can be
* filtered (by rules, by file names)
* sorted
* grouped (rows can be grouped, groups can be collapsed, expanded)

If there are many, many violations in the diff report, the file might also be very very big, potentially make your browser explode.
We could lazily fetch/load additional results. That would increase the initial load time.

Another useful feature would be, to fetch the code snippets and integrate them directly in the report. Currently you have a link to the github code, where the violation occurred, but that means, you need another browser tab. The code snippet could be shown by expanding a row. The overall size of the report must be considered: if we directly embed the code snippets, then the report is ever bigger. So, maybe just integrate it via iframe/fetch on demand.

One possible solution could be, to use https://datatables.net/

**Comment by oowekyala** [comment]
Possible solution to embed code snippets: https://gist-it.appspot.com/
